ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8
ENV SB_FOLDER="/data"
ENV SB_PORT=8099
ENV SB_HOSTNAME="0.0.0.0"

USER root

EXPOSE 8099

# ENTRYPOINT []

# CMD ["mkdir -p /data/vault && chown -R /data/vault && /tini", "--", "deno", "run", "-A", "--unstable", "/silverbullet.js"]
